//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vesper.LogBook.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boat
    {
        public int BoatId { get; set; }
        public string Name { get; set; }
        public string Make { get; set; }
        public int Size { get; set; }
        public string Type { get; set; }
        public string CurrentRigging { get; set; }
        public string RiggingAvailable { get; set; }
        public string UseRestrictions { get; set; }
        public string Status { get; set; }
        public string OwnedBy { get; set; }
    }
}
