//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vesper.LogBook.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoatStatusLog
    {
        public int BoatStatusLogId { get; set; }
        public string BoatName { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> RemovalOfServiceDate { get; set; }
        public string CommentOnReturn { get; set; }
        public Nullable<System.DateTime> ReturnToServiceDate { get; set; }
    }
}
