//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vesper.LogBook.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boating
    {
        public int BoatingId { get; set; }
        public int LogBookId { get; set; }
        public int MemberId { get; set; }
        public string Seat { get; set; }
        public int Order { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual LogBook LogBook { get; set; }
    }
}
