//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vesper.LogBook.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogBook()
        {
            this.Boatings = new HashSet<Boating>();
        }
    
        public int LogBookId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<int> MilesRowed { get; set; }
        public string Comment { get; set; }
        public string BoatName { get; set; }
        public string BoatType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boating> Boatings { get; set; }
    }
}
