//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vesper.LogBook.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VesperLogBookEntities : DbContext
    {
        public VesperLogBookEntities()
            : base("name=VesperLogBookEntities")
        {
        }
    
    		public VesperLogBookEntities(string connectionString)
            : base(connectionString)
        {
    		Database.Log = s => System.Diagnostics.Debug.WriteLine(s);        
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Boat> Boats { get; set; }
        public virtual DbSet<LogBook> LogBooks { get; set; }
        public virtual DbSet<BoatStatusLog> BoatStatusLogs { get; set; }
        public virtual DbSet<BoatType> BoatTypes { get; set; }
    }
}
